
/**
 * Represents a single data point in a time series for a stock chart.
 * Educational note: This structure is fundamental for any kind of financial chart visualization.
 */
export interface StockDataPoint {
  date: string;
  price: number;
  forecast?: number; // Optional: for DL agent's predictions
}

/**
 * Represents a trading signal generated by an agent (e.g., ML Agent).
 * Educational note: Signals are discrete events that suggest a trading action.
 * They are the output of a prediction model.
 */
export interface TradeSignal {
  date: string;
  type: 'buy' | 'sell';
  price: number;
  reason: string; // Educational explanation of the signal
}

/**
 * Represents a news article fetched and processed by the Market News Agent.
 * Educational note: Integrating unstructured data like news requires NLP techniques
 * for summarization and sentiment analysis.
 */
export interface NewsItem {
  headline: string;
  summary: string;
  sentiment: 'Positive' | 'Negative' | 'Neutral';
  source: string;
}

/**
 * Represents a section of the AI-generated financial report.
 * Educational note: Structuring large text outputs from LLMs into logical sections
 * makes the information much more digestible for the user.
 */
export interface ReportSection {
  title: string;
  content: string;
}

/**
 * Represents a piece of advice or feedback from the Personalized Mentor Agent.
 */
export interface MentorTip {
  id: number;
  title: string;
  content: string;
  relatedAgent: 'Report' | 'News' | 'Trading' | 'General';
}

/**
 * Represents the performance metrics of the Reinforcement Learning agent.
 * Educational note: P/L (Profit/Loss) is a primary reward signal in financial RL.
 */
export interface RLAgentPerformance {
    profitOrLoss: number;
    trades: number;
    winRate: number;
}
